services:
  app:
    image: node:22 # or any Node.js version you're using
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/test123
      - SESSION_SECRET=dupa
      - PRODUCTION_TEST=true
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    depends_on:
      - mongodb
    command: >
      sh -c "npm install && npm start"

  mongodb:
    image: mongo:bionic # or your desired MongoDB version
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
    driver: local